[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/webdesight.hu"
  to = "/webrebirth.hu"
  status = 391
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
