[[redirects]]
from = "https://webdesight.hu/*"
to = "https://www.webrebirth.hu/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.webdesight.hu/*"
to = "https://www.webrebirth.hu/:splat"
status = 301
force = true

[build.environment]

[context.production.branch-deploy]
    command = "mv robots-disallow.txt robots.txt"


[context.production]
    command = "mv robots-production.txt robots.txt"


